add config option to disable location section
yaahc/color-eyre pull request #106
Opened 2022-03-17 16:56 UTC by Emilgardis

implements #105

I'm not sure how to handle the panic hook.
I think it makes sense to always display the location even if we've set the config to false.

If this is unexpected (I think it isn't), it should be possible to implement by adding a field to `DefaultPanicMessage`

2022-03-17 18:32 UTC, yaahc requested changes
looks great, just need a few more cfgs. Also, and this one isn't mandatory, but if you wanted to add an example to the doc comment for the method including the output and or a test that would be greatly appreciated.

2022-03-17 18:37 UTC, Emilgardis commented on src/config.rs
> +    display_location_section: bool,
I opted to not add it behind a gate for being consistent with how capture_span_trace_by_default is not gated. I'll fix it if that's the preference though :+1:

2022-03-17 18:42 UTC, yaahc commented on src/config.rs
> +    display_location_section: bool,
> I opted to not add it behind a gate for being consistent with how capture_span_trace_by_default is not gated. I'll fix it if that's the preference though 👍

ah yea, that's a bit of technical debt, I've been meaning to switch things around for a while and make spantrace capture disabled by default and cutting a new breaking change release, but I haven't been good about making time cleanup work on color-eyre >_<

2022-03-17 20:36 UTC, yaahc approved these changes

2022-03-17 20:53 UTC, Emilgardis commented
hmm, [that failure](https://github.com/yaahc/color-eyre/runs/5591824532?check_suite_focus=true) is annoying. Can fix with a cfg on the test file I think

2022-04-08 16:56 UTC, Emilgardis commented
fixed the build error, remembered I had this pr and figured I'd fix it while on the phone, using dev.github.com seems promising, but it's not too great 😅

2022-07-11 18:22 UTC, merged

2022-07-11 18:26 UTC, Emilgardis commented
No worries! I know you're busy :D